import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import { useRouter } from "next/router";
import { DashboardRoutes, ICreateNoteDto } from "shared";

import { DashboardLayout } from "@/components/layout/Dashboard";
import { CreateNote } from "@/components/templates/CreateNote/CreateNote";

export default function Dashboard() {
  const router = useRouter();

  const onCreateNote = (dto: ICreateNoteDto) => {
    console.log(dto);
    router.push(DashboardRoutes.Dashboard);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <DashboardLayout>
        <CreateNote onCreateNote={onCreateNote} />
      </DashboardLayout>
    </>
  );
}

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string)),
    },
  };
};
