version: "3.8"

services:
  postgres:
    image: postgres:latest
    env_file:
      - ./apps/backend/.env
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
