import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import { useRouter } from "next/router";
import { DashboardRoutes, ICreateNoteDto } from "shared";

import { DashboardLayout } from "@/components/layout/Dashboard";
import { CrudNote } from "@/components/templates/CrudNote/CrudNote";

const AddNote = () => {
  const router = useRouter();

  const createHandler = async (dto: ICreateNoteDto) => {
    console.log(dto);

    await new Promise((res) => {
      setTimeout(() => {
        res("resolve");
      }, 500);
    });

    router.push(DashboardRoutes.Notes);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CrudNote onCrud={createHandler} />
    </>
  );
};

export default AddNote;
AddNote.getLayout = function getLayout(page: React.ReactNode) {
  return <DashboardLayout>{page}</DashboardLayout>;
};

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string)),
    },
  };
};
