import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import { useRouter } from "next/router";
import { AuthInput, DashboardRoutes } from "shared";

import { AuthLayout } from "@/components/layout/Auth";
import { SignIn } from "@/components/templates/SignIn/SignIn";

import { useAuth } from "@/hooks/useAuth";

const SignInPage = () => {
  const { signIn } = useAuth();
  const router = useRouter();

  const signInHandler = async (dto: AuthInput) => {
    try {
      await signIn(dto);
      router.push(DashboardRoutes.Dashboard);
    } catch (error) {
      console.log(error);
    }
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <SignIn signInHandler={signInHandler} />
    </>
  );
};

export default SignInPage;
SignInPage.getLayout = function getLayout(page: React.ReactNode) {
  return <AuthLayout>{page}</AuthLayout>;
};

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string)),
    },
  };
};
