import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import { useState } from "react";
import { Button, ConfirmModal } from "ui";

import { DashboardLayout } from "@/components/layout/Dashboard";

const Dashboard = () => {
  const [isOpen, setIsOpen] = useState(false);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button text="open" onClick={() => setIsOpen(true)} />
      <ConfirmModal
        title="confirm"
        info="confirm info"
        isOpen={isOpen}
        declineButton={{ text: "Decline" }}
        confirmButton={{ text: "Confirm" }}
        closeHandler={() => setIsOpen(false)}
      />
    </>
  );
};

export default Dashboard;
Dashboard.getLayout = function getLayout(page: React.ReactNode) {
  return <DashboardLayout>{page}</DashboardLayout>;
};

export const getServerSideProps: GetServerSideProps = async ({ locale }) => {
  return {
    props: {
      ...(await serverSideTranslations(locale as string)),
    },
  };
};
