import Head from "next/head";
import { Input, InputField } from "ui";

import { AuthForm } from "@/components/auth/Form";

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <AuthForm />
    </>
  );
}
