import { GetServerSideProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Head from "next/head";
import { useRouter } from "next/router";
import { DashboardRoutes, IUpdateNoteDto } from "shared";

import { DashboardLayout } from "@/components/layout/Dashboard";
import { CrudNote } from "@/components/templates/CrudNote/CrudNote";

import { useApi } from "@/hooks";
import { ApiNoteResponse } from "@/pages/api/dashboard/note";

const Note = () => {
  const router = useRouter();
  const { data } = useApi<ApiNoteResponse>({
    endpoint: "/api/dashboard/note",
    params: { id: router.query.id },
    onSuccess(data) {
      if (data?.note) return;

      // router.push("/404");
    },
  });

  const editHandler = async (dto: IUpdateNoteDto) => {
    console.log(dto);

    await new Promise((res) => {
      setTimeout(() => {
        res("resolve");
      }, 500);
    });

    router.push(DashboardRoutes.Notes);
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {data?.note && <CrudNote onCrud={editHandler} note={data.note} />}
    </>
  );
};

export default Note;
Note.getLayout = function getLayout(page: React.ReactNode) {
  return <DashboardLayout>{page}</DashboardLayout>;
};

export const getServerSideProps: GetServerSideProps = async ({
  params,
  locale,
}) => {
  if (!params || !params.id) return { notFound: true };

  return {
    props: {
      ...(await serverSideTranslations(locale as string)),
    },
  };
};
